### ISSUE TITLE
HECVAT Lite.

### ISSUE THREAD

**Issue by Carreau** [jupyter/security#13]
Received on the security mailing list:

```
We are in the process of vetting software for purchase and we are wondering if you are able to provide a Higher Education Community Vendor Assessment Toolkit (HECVAT) for our

documentation and decision making process.  I have attached a copy of the assessment to this email, if you have any questions please let me know
```

[HECVAT-Lite.xlsx](https://github.com/jupyter/security/files/7341612/HECVAT-Lite.xlsx)

I'm not sure if the Jupyter organisation qualifies as a vendor and can provide that. If anybody has experience with that, maybe Trusted CI ?

**Comment by Carreau** [comment]
I got the same response from what @rpwagner  is saying from internal Quansight questions. And looking at the questions in the XLS, there is about only 20% if not less that apply to jupyter as an organisation, numfocus could fill a bit more, but it's true that 2i2c / anaconda/ another vendor might be better suited for this specific request right now.

I'll respond and also mention that we are engaging with https://www.trustedci.org/

**Comment by djclarkson** [comment]
You (or others with similar challenges) can reach out to us at https://www.hecvatpro.com
