### ISSUE TITLE
Mail to security@ipython.org bounced

### ISSUE THREAD

**Issue by weddige** [jupyter/security#50]
I tried to report a vulneravility in IPython to  security@ipython.org, but my mail bounced:

> Hello [my email address],
>
> We're writing to let you know that the group you tried to contact (ipython-security) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> 
>  * You might have spelled or formatted the group name incorrectly.
>  * The owner of the group may have removed this group.
>  * You may need to join the group before receiving permission to post.
>  * This group may not be open to posting.
> 
> If you have questions related to this or any other Google Group, visit the Help Center at https://groups.google.com/support/

If you need more details to debug the issue, please feel free to contact me. I already reported the vulnerability via Tidelift, as suggested in https://github.com/ipython/ipython/security/policy.

**Comment by rcthomas** [comment]
Thanks for the report @weddige, we've addressed the issue that was causing this.  You should expect to hear back on your specific issue directly.  Thank you.
